server:
  port: 8099

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/bank/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

        - id: purchase-service
          uri: lb://purchase-service
          predicates:
            - Path=/purchases/** 

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/** 